FROM gems_installed:latest

MAINTAINER Quinn Shanahan q.shanahan@gmail.com
# http://www.activestate.com/blog/2014/01/using-docker-run-ruby-rspec-ci-jenkins

# VOLUME ["/home/quinn/quill-platform"]

# RUN cd /quill-platform && \
    # cd    quill            && bundle install && \
    # cd ../questions-module && bundle install && \
    # cd ../api              && bundle install \
